# Generated by Django 3.1.4 on 2021-03-21 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('news_id', models.IntegerField(primary_key=True, serialize=False)),
                ('section', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('headline', models.CharField(max_length=255)),
                ('image', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('content', models.CharField(max_length=255)),
            ],
        ),
    ]
