# Generated by Django 3.1.4 on 2021-03-28 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20210328_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reader',
            name='has_read',
            field=models.ForeignKey(db_column='news_id', on_delete=django.db.models.deletion.CASCADE, to='news.news'),
        ),
    ]
