# Generated by Django 3.1.4 on 2021-03-28 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_auto_20210328_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reader',
            name='has_read',
            field=models.CharField(max_length=255),
        ),
    ]
